In [38]:

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import sklearn

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

#TASK 1 : reading in the csv file
fruit_data = pd.read_table("C:/Users/latma/OneDrive/Documents/ComputerScience_Yr2/Machine_Learning/data sets/fruit_data_with_colors.txt")
fruit_data.head()

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [12]:
#TASK 2 :
fruit_vector=fruit_data[["mass","width","height","color_score", "fruit_name"]]
fruit_vector.head()
#Extract the mass, width, height and color_score data from the test set as variable X
#and fruit_name as y
X = fruit_vector.iloc[:,:-1].values #all rows, all columns up to the end. .values returns a numpy
y = fruit_vector.iloc[:, -1].values # all the rows, only column 4 (could also write [:, -1])
#print(X[0:4])
#print(y[0:4])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=4321)

for i in range(1,9):  
    
    scaler = StandardScaler()
    scaler.fit(X_train)

    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test)


    classifier = KNeighborsClassifier(n_neighbors=i)
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    print("Neighbours: ", i)
    print(confusion_matrix(y_test, y_pred))
    print("kNN %:", metrics.accuracy_score(y_test, y_pred)*100)


Neighbours:  1
[[7 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 6]]
kNN %: 100.0
Neighbours:  2
[[7 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 6]]
kNN %: 100.0
Neighbours:  3
[[7 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 6]]
kNN %: 100.0
Neighbours:  4
[[7 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 6]]
kNN %: 100.0
Neighbours:  5
[[4 0 0 3]
 [0 2 0 0]
 [0 3 0 0]
 [0 0 0 6]]
kNN %: 66.66666666666666
Neighbours:  6
[[4 0 0 3]
 [0 2 0 0]
 [0 3 0 0]
 [0 1 0 5]]
kNN %: 61.111111111111114
Neighbours:  7
[[2 0 0 5]
 [0 2 0 0]
 [0 2 0 1]
 [0 0 0 6]]
kNN %: 55.55555555555556
Neighbours:  8
[[2 0 0 5]
 [0 2 0 0]
 [0 2 0 1]
 [0 2 0 4]]
kNN %: 44.44444444444444


In [10]:
#TASK 3 : Naive Bayes version
classifier_B = sklearn.naive_bayes.GaussianNB()
classifier_B.fit(X_train, y_train)
y_pred_B = classifier_B.predict(X_test)
print(confusion_matrix(y_test, y_pred_B))
print("Naive Bayes %):", metrics.accuracy_score(y_test, y_pred_B)*100)

[[7 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [2 0 0 4]]
Naive Bayes %): 88.88888888888889


In [21]:
#TASK 4 :

#TRAINING------------------------

totalNoFruit = len(X_train)
#Total number of each fruit in the training set (i.e. a_N = total number of apples)
a_N = 0
m_N = 0
o_N = 0
l_N = 0

#means
Apples_counter = [0,0,0,0]
Mandarin_counter =[0,0,0,0]
Orange_counter = [0,0,0,0]
Lemon_counter = [0,0,0,0]

Means = [0,0,0,0]

#varinaces
Apples_var = [0,0,0,0]
Mandarin_var =[0,0,0,0]
Orange_var = [0,0,0,0]
Lemon_var = [0,0,0,0]
Variances = [Apples_var, Mandarin_var, Orange_var, Lemon_var]

#calcutes the sum of all the values of each feature for a class
def sumCalc (row, counter):   
    counter[0] += row[0]
    counter[1] += row[1]
    counter[2] += row[2]
    counter[3] += row[3]

    return counter

#uses the sums previously calculated to calculate the means for each feature of each class
def meanCalc(counter, N):
    means = []
    for s in counter:
        m = s/N # could add a rounding here
        means.append(m)
    return means

#calcultes the sum of squares for each feature of a class
def sumOfSqurs(row, means, var):
    var[0] += (row[0]-means[0])**2
    var[1] += (row[1]-means[1])**2
    var[2] += (row[2]-means[2])**2
    var[3] += (row[3]-means[3])**2
    return var

#calcultes the variance for each feature of each class
def VarianceCalc(var, N):
    var[0] = var[0]/(N-1)
    var[1] = var[1]/(N-1)
    var[2] = var[2]/(N-1)
    var[3] = var[3]/(N-1)
    return var
    
#first pass to calc the sums
for i in range(totalNoFruit):
    if(y_train[i] == "apple"):
        Apples_counter = sumCalc(X_train[i], Apples_counter)
        a_N += 1
    elif(y_train[i] == "mandarin"):
        Mandarin_counter = sumCalc(X_train[i], Mandarin_counter)
        m_N += 1
    elif(y_train[i] == "orange"):
        Orange_counter = sumCalc(X_train[i], Orange_counter)
        o_N += 1
    elif(y_train[i] == "lemon"):
        Lemon_counter = sumCalc(X_train[i], Lemon_counter)
        l_N += 1

        # converting the sums into means 
Means[0] = meanCalc(Apples_counter,a_N)
Means[1]= meanCalc(Mandarin_counter,m_N)
Means[2]= meanCalc(Orange_counter,o_N)
Means[3]= meanCalc(Lemon_counter,l_N)


#second pass ot cal the sum of differnece to for the variance
for i in range(totalNoFruit):
    if(y_train[i] == "apple"):
        Apples_var = sumOfSqurs(X_train[i], Means[0], Apples_var)
    elif(y_train[i] == "mandarin"):
        Mandarin_var = sumOfSqurs(X_train[i], Means[1], Mandarin_var)
    elif(y_train[i] == "orange"):
        Orange_var = sumOfSqurs(X_train[i], Means[2], Orange_var)
    elif(y_train[i] == "lemon"):
        Lemon_var = sumOfSqurs(X_train[i], Means[3], Lemon_var)


#actually calculating all of the variances
Apples_var = VarianceCalc(Apples_var, a_N)
Mandarin_var = VarianceCalc(Mandarin_var, m_N)
Orange_var = VarianceCalc(Orange_var, o_N)
Lemon_var = VarianceCalc(Lemon_var, l_N)

#class probablilty the  P(c)
classProbabilities = [a_N/totalNoFruit, m_N/totalNoFruit, o_N/totalNoFruit, l_N/totalNoFruit]


In [22]:
#TESTING-------------------------------------
import math

totatNoTests =  len(X_test)
numOfFeatures = 4
X_prediction = []

curr_PcXs = []

#calcultes the probablity of x given C
def P_of_XgivenC(x,m,v):
    denominator = (2*math.pi*v)**.5
    numumirator = math.exp(-((float(x) - float(m))**2)/(2*v))
    return numumirator/denominator

#calcultes the sum of all the logs of each of the p xis
def sumLogs(pcx):
    total = 0
    for x in pcx:
        if(x != 0.0):
            total += math.log(x,10)    
    return 10 ** total

#probablity of each fruit
P_apple = []
P_mandarin = []
P_orange = []
P_lemon = []

#calcultes the probabilty of each fruit
def P_fruit(P,fruit):
    for i in range(totatNoTests):
        #calculating the probabilty that its an apple
        P_of_cGivenX = [0,0,0,0]
        for j in range(numOfFeatures):
            P_of_cGivenX[j] = P_of_XgivenC(X_test[i][j], Means[fruit][j], Variances[fruit][j])

        P.append(abs(sumLogs(P_of_cGivenX) * classProbabilities[0])) 
    return P

P_apple = P_fruit(P_apple,0)
P_mandarin = P_fruit(P_mandarin,1)
P_orange = P_fruit(P_orange,2)
P_lemon = P_fruit(P_lemon,3)
        

In [32]:
#assigning the prediction label
y_pred = []
y_test2 = []

def fruitToNum(f):
    if f == "apple":
        return 0
    elif f == "mandarin":
        return 1
    elif f == "orange":
        return 2
    elif f == "lemon":
        return 3
    else:
        return -1

#assigning the max porbailyt of each of the classes to be the vectors label
for i in range(totatNoTests):
    temp_Ps = [P_apple[i], P_mandarin[i], P_orange[i], P_lemon[i]]
    #print(temp_Ps)
    Temp_pred_y = temp_Ps.index(max(temp_Ps))
    y_pred.append(Temp_pred_y)
    
    y_test2.append(fruitToNum(y_test[i]))
    
#print("\npred: ",y_pred)
#print("actu: ",y_test2)

#populating the confusion matrix
confusionMatrix = [[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]

for i in range(totatNoTests):
    x = y_pred[i]
    y = y_test2[i]
    confusionMatrix[x][y] += 1

diagonal = 0  
c = 0
print("Confusion matrix: ")
for row in confusionMatrix:
    diagonal += row[c]
    c+=1
    print("[",*row,"]")

accuracyVal = diagonal/totatNoTests
print("\nAccuracy value: ",accuracyVal*100, "%")
    

Confusion matrix: 
[ 7 0 2 0 ]
[ 0 3 0 0 ]
[ 0 0 4 0 ]
[ 0 0 0 2 ]

Accuracy value:  88.88888888888889 %
