In [4]:
import numpy as np

# initial_P = [L,H]
initial_P = [-1, -1]
#transition_P = [[From L to L, From L to H], [From H to L, From H to L]]
transition_P = [[-0.737, -1.322],[-1, -1]]
#observations_P = [ [LA, LC, LG, LT,], [HA, HC, HG, HT] ]
observations_P = [[-1.737, -2.322, -2.322, -1.737],[-2.322, -1.737, -1.737, -2.322]]

states = ['L','H']
numStates = len(states)
#A=0 C=1 G=2 T=3
obs = ['A','C','G','T']
obs_sequence = ['G','G','C','A','C','T','G','A','A']

#T_probs = [[number of rows] [number of cols]
T_probs = np.zeros([len(states), len(obs_sequence)], dtype=float)
T_maxStates = np.empty([len(states),len(obs_sequence)-1], dtype=int) #0=L 1=H

def letterToNum(letter):
    return obs.index(letter)

#initailinsing T_probs
for i in range(numStates):
    T_probs[i][0] = initial_P[i] + observations_P[i][letterToNum(obs_sequence[0])]


In [5]:
#TASK 1
#populating the table with the probabilities and the storing which max they chose
for c in range(1,len(obs_sequence)):
    currObs = letterToNum(obs_sequence[c])
    for r in range(numStates):
        x = np.empty([numStates])
        for s in range(numStates):
            x[s] = T_probs[s][c - 1] + transition_P[s][r]

        T_probs[r][c] = observations_P[r][currObs] + max(x)
        T_maxStates[r][c-1] = np.argmax(x)

#print("T_probs: \n",T_probs)
print("values: \n",T_probs)
print("decisions: \n", T_maxStates)


values: 
 [[ -3.322  -6.059  -8.796 -10.948 -14.007 -16.481 -19.54  -22.014 -24.488]
 [ -2.737  -5.474  -8.211 -11.533 -14.007 -17.329 -19.54  -22.862 -25.658]]
decisions: 
 [[1 1 1 0 0 0 0 0]
 [1 1 1 0 1 0 1 0]]


In [6]:
#TASK 2
#calculting the starting value of the backtrack
possMaxs = np.empty([numStates])
for i in range(numStates):
    possMaxs[i] = T_probs[i][len(obs_sequence)-1]
startMax = np.argmax(possMaxs)

resultingState = np.empty(len(obs_sequence),dtype=int)
resultingState[len(obs_sequence)-1] = startMax
currMax = startMax

#completing the backtrack
for c in range(len(obs_sequence)-2, -1, -1):
    resultingState[c] = T_maxStates[currMax][c]
    currMax = resultingState[c]

#print("resultingState: ", resultingState)
#creating a letter list of the final state sequence
stateLetters = []
for s in resultingState:
    stateLetters.append(states[s])
print(stateLetters)

['H', 'H', 'H', 'L', 'L', 'L', 'L', 'L', 'L']
